version: "3"

services:
  api:
    container_name: nestjs_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
  postgres:
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: summer
      POSTGRES_PASSWORD: school
      POSTGRES_DB: imdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - nesjs-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - nesjs-network
networks:
  nesjs-network:
volumes:
  database-data:
