version: '3.0'

services:
    api:
        container_name: nestjs_api
        build:
            context: ../
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - ./day3/module0-controllers:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run start:dev
        # restart: unless-stopped
    postgres:
        ports:
          - "5432:5432"
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: martec
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: martec
          PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
          - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
        networks:
            - nesjs-network
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
        networks:
            - nesjs-network
networks:
    nesjs-network:
volumes:
  database-data:
